
'use strict';

module.exports = {
  // solarize dark at top so that it's always the default
  'solarized_dark': 'Solarized (Dark)',
  'solarized_light': 'Solarized (Light)',
  'agate': 'Agate',
  'androidstudio': 'Android Studio',
  // 'arta': 'Arta',
  'ascetic': 'Ascetic',
  'atelier-cave.dark': 'Atelier Cave (Dark)',
  'atelier-cave.light': 'Atelier Cave (Light)',
  // 'atelier-dune.dark': 'Atelier Dune (Dark)',
  // 'atelier-dune.light': 'Atelier Dune (Light)',
  // 'atelier-estuary.dark': 'Atelier Estuary (Dark)',
  // 'atelier-estuary.light': 'Atelier Estuary (Light)',
  // 'atelier-forest.dark': 'Atelier Forest (Dark)',
  // 'atelier-forest.light': 'Atelier Forest (Light)',
  // 'atelier-heath.dark': 'Atelier Heath (Dark)',
  'atelier-heath.light': 'Atelier Heath (Light)',
  // 'atelier-lakeside.dark': 'Atelier Lakeside (Dark)',
  'atelier-lakeside.light': 'Atelier Lakeside (Light)',
  // 'atelier-seaside.dark': 'Atelier Seaside (Dark)',
  // 'atelier-seaside.light': 'Atelier Seaside (Light)',
  // 'atelier-sulphurpool.dark': 'Atelier Sulphurpool (Dark)',
  // 'atelier-sulphurpool.light': 'Atelier Sulphurpool (Light)',
  // 'codepen-embed': 'Codepen Embed',
  // 'color-brewer': 'Color Brewer',
  // 'dark': 'Dark',
  'darkula': 'Darkula',
  // 'docco': 'Docco',
  // 'far': 'Far',
  'foundation': 'Foundation Docs',
  // 'github-gist': 'GitHub Gist',
  'github': 'GitHub',
  // 'googlecode': 'Google Code',
  // 'grayscale': 'Grayscale',
  // 'hopscotch': 'Hopscotch',
  'hybrid': 'Hybrid',
  // 'idea': 'Idea',
  'ir_black': 'IR_Black',
  'kimbie.dark': 'Kimbie (Dark)',
  // 'kimbie.light': 'Kimbie (Light)',
  // 'magula': 'Magula',
  'mono-blue': 'mono-blue',
  // 'monokai': 'Monokai',
  'monokai_sublime': 'Monokai',
  'obsidian': 'Obsidian',
  // 'paraiso.dark': 'Paraiso (Dark)',
  'paraiso.light': 'Paraiso (Light)',
  'railscasts': 'RailsCasts',
  // 'rainbow': 'Rainbow',
  // 'sunburst': 'Sunburst',
  // 'tomorrow-night-blue': 'Tomorrow Night (Blue)',
  // 'tomorrow-night-bright': 'Tomorrow Night (Bright)',
  'tomorrow-night-eighties': 'Tomorrow Night (Eighties)',
  'tomorrow-night': 'Tomorrow Night',
  'tomorrow': 'Tomorrow',
  // 'vs': 'Visual Studio',
  'xcode': 'Xcode',
  'zenburn': 'Zenburn',
};
